; Configurable parameters:
; SERIALCOM_SPEED = speed of the serial port (baud), global [env] section
; HS_DATA_PIN = pin/GPIO for the LED strip data channel, specific [board] section
; HS_CLOCK_PIN = pin/GPIO for the LED strip clock channel, specific [board] section
; LED_POWER_PIN = pin/GPIO for external relay power control, it will turn off (low state) if no serial data is received after 5 seconds
; LED_POWER_INVERT = if defined: off state is a high signal for the power relay, on state is a low signal
; HYPERSERIAL_FASTLED_RGBW_EMULATION = FastLED RGBW handling mode for RGBW builds
;   1 (default): emulate RGBW by blending W into RGB
;   0: disable W blending and output RGB only

; MULTI-SEGMENT SUPPORT
; You can define second segment to handle. Add following parameters (with -D prefix to the build_flags sections).
; SECOND_SEGMENT_START_INDEX = start index of the second segment
; HS_SECOND_SEGMENT_CLOCK_PIN = pin/GPIO for the second segment LED strip data channel
; HS_SECOND_SEGMENT_DATA_PIN = pin/GPIO for the second segment LED strip clock channel
; SECOND_SEGMENT_REVERSED = if defined, the segment is reversed, the first LED of the second segment becomes the last
; For example: we have first LED strip with 512 leds and the second LED strip with 400 leds.
; For such configuration you need to set SECOND_SEGMENT_START_INDEX to 512 here, compile and upload the firmware.
; In HyperHDR you should have a single LED strip that contains 912 leds.
; SECOND_SEGMENT_REVERSED could be helpful if you start both segments in the middle of the bottom edge and join again at the top (both ends).
; Example build string for the second segment (append it to the global [env] or to the specific [board] section):
; build_flags = ... -DSECOND_SEGMENT_START_INDEX=450 -DHS_SECOND_SEGMENT_DATA_PIN=4 -DSECOND_SEGMENT_REVERSED


[platformio]
default_envs = XIAO_S3_SK6812_RGBW_COLD

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
lib_deps = FastLED
extra_scripts = pre:extra_script.py
build_flags = 
    -D SERIALCOM_SPEED=2000000

;==========================================================
; Xiao ESP32S3 board
;==========================================================
[xiao_esp32s3]
board = seeed_xiao_esp32s3
build_flags =
    -D FASTLED_ESP32_I2S_NUM_DMA_BUFFERS=4
    -D HS_MULTICORE

[env:XIAO_S3_SK6812_RGBW_COLD]
extends = xiao_esp32s3
board = seeed_xiao_esp32s3
build_flags =
    -D NEOPIXEL_RGBW
    -D COLD_WHITE
    -D HS_DATA_PIN=9
    ${xiao_esp32s3.build_flags}
    ${env.build_flags}
custom_prog_version = XIAO_S3_SK6812_RGBW_COLD
