; Configurable parameters:
; SERIALCOM_SPEED = speed of the serial port (baud), global [env] section
; HS_DATA_PIN = pin/GPIO for the LED strip data channel, specific [board] section
; HS_CLOCK_PIN = pin/GPIO for the LED strip clock channel, specific [board] section
; LED_POWER_PIN = pin/GPIO for external relay power control, it will turn off (low state) if no serial data is received after 5 seconds
; LED_POWER_INVERT = if defined: off state is a high signal for the power relay, on state is a low signal

; MULTI-SEGMENT SUPPORT
; You can define second segment to handle. Add following parameters (with -D prefix to the build_flags sections).
; HS_SECOND_SEGMENT_START_INDEX = start index of the second segment
; HS_SECOND_SEGMENT_CLOCK_PIN = pin/GPIO for the second segment LED strip data channel
; HS_SECOND_SEGMENT_DATA_PIN = pin/GPIO for the second segment LED strip clock channel
; SECOND_SEGMENT_REVERSED = if defined, the segment is reversed, the first LED of the second segment becomes the last
; For example: we have first LED strip with 512 leds and the second LED strip with 400 leds.
; For such configuration you need to set HS_SECOND_SEGMENT_START_INDEX to 512 here, compile and upload the firmware.
; In HyperHDR you should have a single LED strip that contains 912 leds.
; SECOND_SEGMENT_REVERSED could be helpful if you start both segments in the middle of the bottom edge and join again at the top (both ends).
; Example build string for the second segment (append it to the global [env] or to the specific [board] section):
; build_flags = ... -DHS_SECOND_SEGMENT_START_INDEX=450 -DHS_SECOND_SEGMENT_DATA_PIN=4 -DSECOND_SEGMENT_REVERSED


[platformio]
default_envs = HyperSerial_ESP32

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
lib_deps = FastLED/FastLED@^3.10.3
extra_scripts = pre:extra_script.py
build_flags = 
    -D SERIALCOM_SPEED=2000000

;==========================================================
; HyperSerial ESP32 firmware configuration for custom board
;==========================================================

[env:HyperSerial_ESP32]
board = seeed_xiao_esp32s3 ; change to your board
build_flags =
    -D FASTLED_ESP32_I2S_NUM_DMA_BUFFERS=4
    -D HS_MULTICORE ; comment if using ESP32C3 since its single core
    ;-D HS_NEO_PIXEL_RGB ; uncomment if your LED strip is RGB, comment if it is RGBW
    -D HS_NEOPIXEL_RGBW ; uncomment if your LED strip is RGBW, comment if it is RGB
    -D HS_COLD_WHITE ; remove if led strip is NEUTRAL_WHITE or WARM_WHITE
    -D HS_DATA_PIN=9 ; change to your data pin
    ;-D HS_CLOCK_PIN=10 ; uncomment and change to your clock pin if you are using a clocked LED strip (SPI or APA102)
    ;-D LED_POWER_PIN=5
    ;-D LED_POWER_INVERT
    ;-D HS_SECOND_SEGMENT_START_INDEX=301
    ;-D HS_SECOND_SEGMENT_DATA_PIN=4
    ;-D HS_SECOND_SEGMENT_CLOCK_PIN=5
    ${env.build_flags}
custom_prog_version = HyperSerial_ESP32

