/* adalight.cpp
*
*  MIT License
*
*  Copyright (c) 2021-2026 awawa-dev
*
*  https://github.com/awawa-dev/HyperSerialESP32
*
*  Permission is hereby granted, free of charge, to any person obtaining a copy
*  of this software and associated documentation files (the "Software"), to deal
*  in the Software without restriction, including without limitation the rights
*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*  copies of the Software, and to permit persons to whom the Software is
*  furnished to do so, subject to the following conditions:
*
*  The above copyright notice and this permission notice shall be included in all
*  copies or substantial portions of the Software.

*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*  SOFTWARE.
 */

#include <Arduino.h>
#include "fastled_adapter.h"

///////////////////////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE. ADJUST THE CONFIGURATION IN THE platformio.ini //
///////////////////////////////////////////////////////////////////////////

#define _STR(x) #x
#define _XSTR(x) _STR(x)
#define VAR_NAME_VALUE(var) #var " = " _XSTR(var)
#define _XSTR2(x,y) _STR(x) _STR(y)
#define VAR_NAME_VALUE2(var) #var " = " _XSTR2(var)

#define SerialPort Serial

#ifdef LED_POWER_PIN
	#include "powercontrol.h"
#endif

#include "adalight.h"
#include <freertos/semphr.h>

#if defined(CONFIG_IDF_TARGET_ESP32C3)
	#define HS_MULTICORE 0
#else
	#define HS_MULTICORE 1
#endif

void setup()
{
	// Init serial port
	Serial.setRxBufferSize(MAX_BUFFER - 1);
	Serial.setTimeout(50);
	Serial.begin(SERIALCOM_SPEED);
	while (!Serial) continue;

	#if defined(NEOPIXEL_RGBW) || defined(NEOPIXEL_RGB)
		#ifdef NEOPIXEL_RGBW
			#ifdef COLD_WHITE
				calibrationConfig.setParamsAndPrepareCalibration(0xFF, 0xA0, 0xA0, 0xA0);
			#else
				calibrationConfig.setParamsAndPrepareCalibration(0xFF, 0xB0, 0xB0, 0x70);
			#endif
		#endif
	#endif

	#if !defined(CONFIG_IDF_TARGET_ESP32S2)
		// Display config
		Serial.println(HELLO_MESSAGE);
		#if defined(SECOND_SEGMENT_START_INDEX)
			Serial.write("SECOND_SEGMENT_START_INDEX = ");
			Serial.println(SECOND_SEGMENT_START_INDEX);
		#endif

		// Colorspace/Led type info
		#if defined(NEOPIXEL_RGBW) || defined(NEOPIXEL_RGB)
			#ifdef NEOPIXEL_RGBW
				#if HYPERSERIAL_FASTLED_RGBW_EMULATION
					#ifdef COLD_WHITE
						Serial.println("FastLED SK6812 cold GRBW (RGBW emulation). ");
					#else
						Serial.println("FastLED SK6812 neutral GRBW (RGBW emulation). ");
					#endif
				#else
					#ifdef COLD_WHITE
						Serial.println("FastLED SK6812 cold GRBW (W channel disabled). ");
					#else
						Serial.println("FastLED SK6812 neutral GRBW (W channel disabled). ");
					#endif
				#endif
				calibrationConfig.printCalibration();
			#else
				Serial.println("FastLED ws281x type (GRB).");
			#endif
		#elif defined(SPILED_APA102)
			Serial.println("SPI APA102 compatible type (BGR).");
		#elif defined(SPILED_WS2801)
			Serial.println("SPI WS2801 (RBG).");
		#endif

		delay(50);
	#endif

	#if defined(LED_POWER_PIN)
		Serial.write("LED_POWER_PIN = ");
		Serial.println(LED_POWER_PIN);
		powerControl.init();
	#endif

#ifdef HS_MULTICORE
		adalight.setupMultiCore();
#endif
}

void loop()
{
#if !defined(HS_MULTICORE)
	adalight.serialTaskHandler();
	adalight.processData();
#endif
}

